# Permalinks
permalink:        pretty

# Setup
title:            Alexander Schneider
tagline:
url:              http://wegi.github.io
paginate:         1
baseurl:          http://wegi.github.io/
author:
  name:           Alexander Schneider
  url:            https://twitter.com/DaRealWeGi
  email:          alexander@schneider.gg

# Custom vars
version:          1.0.0
github:
  repo:           https://github.com/wegi/wegi.github.io

pages_list:
  About: '/about'
  Publications: '/publications'
  Archive: '/archive'
  Feed: '/atom.xml'
